<a href="https://colab.research.google.com/github/harene634/Machine-Learning/blob/main/numpy_BYTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a=np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
from numpy import random
x=random.rand(5)
x

array([0.9770434 , 0.80254166, 0.93320418, 0.30075654, 0.13130332])

In [ ]:
c=np.full((2,2),7)
c

array([[7, 7],
       [7, 7]])

In [ ]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.linspace(0,1,num=8,retstep=0.2)

(array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
        0.71428571, 0.85714286, 1.        ]),
 0.14285714285714285)

In [ ]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a[0,0:3]

array([1, 2, 3])

In [ ]:
a.shape

(2, 3)

In [ ]:
a[0][0]=23

In [ ]:
a

array([[23,  2,  3],
       [ 2,  3,  4]])

In [ ]:
a=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8],[2,6,1,2]])
a.shape

(4, 4)

In [ ]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8],
       [2, 6, 1, 2]])

In [ ]:
c1=a[:,1]
c2=a[:,1:2]
print(c1)
print("ew")
print(c2)

[2 3 6]
ew
[[2]
 [3]
 [6]]


In [ ]:
a+=20
a

array([[61, 62, 63, 64],
       [62, 63, 64, 65],
       [65, 66, 67, 68],
       [62, 66, 61, 62]])

In [ ]:
boo=a>25
boo

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [ ]:
np.argmax(a)

11

In [ ]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [2, 0, 3, 1]])

In [ ]:
np.argmin(a)

0

In [ ]:
np.argsort(a)[::-1]

array([[2, 0, 3, 1],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.append(a,[2,3,4,5,7,8])

array([61, 62, 63, 64, 62, 63, 64, 65, 65, 66, 67, 68, 62, 66, 61, 62,  2,
        3,  4,  5,  7,  8])

In [ ]:
np.delete(a,[2,6])

array([61, 62, 64, 62, 63, 65, 65, 66, 67, 68, 62, 66, 61, 62])

In [ ]:
np.where(a>2)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [ ]:
a

array([[61, 62, 63, 64],
       [62, 63, 64, 65],
       [65, 66, 67, 68],
       [62, 66, 61, 62]])

In [ ]:
np.sum(a)

1021

In [ ]:
x=np.array([[1,2],[2,4]])
y=np.array([[2,4],[6,7]])
x.dot(y)

array([[14, 18],
       [28, 36]])

In [ ]:
x.reshape(-2)

array([1, 2, 2, 4])

In [ ]:
x

array([[1, 2],
       [2, 4]])

In [ ]:
https://www.kaggle.com/code/mitulgargsam/stutter-detection